# postgres:
#   image: postgres:10.4-alpine
#   ports:
#     - 5433:5432
#   environment:
#     POSTGRES_USER: pguser3000
#     POSTGRES_PASSWORD: pguser3000
#     POSTGRES_DB: node_postgres
#   # volumes:
#     # - ./src/db_setup:/docker-entrypoint-initdb.d/

# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:10.4-alpine
    # restart: always
    environment:
      POSTGRES_USER: pguser3000
      POSTGRES_PASSWORD: pguser3000
      POSTGRES_DB: node_postgres
    ports:
      - 5433:5432

  adminer:
    image: adminer
    # restart: always
    ports:
      - 8080:8080